
DECLARE @valor INT
DECLARE @resposta INT

SET @valor = 3	
SET @resposta = @valor % 2 

IF(@resposta <> 0)
PRINT 'impar'
ELSE
PRINT 'par'


--Estrutura de repetição
DECLARE @CONTADOR INT = 1

WHILE @CONTADOR <= 1
BEGIN
SET @CONTADOR += 1
PRINT @CONTADOR
END

--FAÇA UM PROGRAMA QUE ESCREVA UMA LISTAGEM DE NUMEROS NA TELA DE 1 A 100, POREM
-- QUANDO UM NUMERO FOR PAR, ESCREVA CONTADOR: NUMERO PAR
-- QUANDO UM NÚMERO FOR IMPAR, ESCREVA CONTADOR: NUMERO IMPAR

DECLARE @CONTADOR INT = -1

WHILE @CONTADOR <= 100
BEGIN
SET @CONTADOR += 1

IF((@CONTADOR % 2) = 0)
PRINT 'CONTADOR: ' + CAST(@CONTADOR AS VARCHAR(10)) + ' É PAR'

ELSE
PRINT 'CONTADOR: ' + CAST(@CONTADOR AS VARCHAR(10)) + ' É ÍMPAR'

END

--DESAFIO DO PROGRAMADOR
--LISTAR OS NUMEROS NA TELA DE 1 A 100 MOSTRAR APENAS OS NUMEROS IMPARES MULTIPLOS DE 3
--MOSTRAR AO FINAL A SOMATÓRIA DOS NUMEROS IMPARES MULTIPLOS DE 3


DECLARE @CONTADOR INT = 0
DECLARE @TOTAL INT = 0

WHILE @CONTADOR <= 100
BEGIN
SET @CONTADOR += 1

IF(@CONTADOR % 2) <> 0
BEGIN
IF((@CONTADOR % 3) = 0)
SET @TOTAL = @CONTADOR + @TOTAL
END

IF((@CONTADOR % 3) = 0)
PRINT 'CONTADOR: ' + CAST(@CONTADOR AS VARCHAR(10)) + ' É DIVISIVEL POR 3'
END

PRINT @TOTAL

-- ==============================

DECLARE @CONTADOR INT = 230

WHILE @CONTADOR <= 496
BEGIN

IF(@CONTADOR > 299 AND @CONTADOR < 497)
	SET @CONTADOR += 5
ELSE 
	SET @CONTADOR += 3

PRINT @CONTADOR
END

--================================================

SELECT * FROM  dbo.EMAIL

SELECT * FROM CAMPANHA FROM dbo.EMAIL

SELECT * FROM CAMPANHA
ALTER TABLE CAMPANHA 
ADD SITUACAO VARCHAR(20)

DECLARE @CONTALINHAS INT = 1
DECLARE @TOTALLINHAS INT

SELECT @TOTALLINHAS = COUNT(*) FROM CAMPANHA

--PRINT @TOTALLINHAS

WHILE @CONTALINHAS <= @TOTALLINHAS
BEGIN
 UPDATE CAMPANHA
 SET SITUACAO = 'ENVIADO'
 WHERE FirstName LIKE ('E%') AND ID = @CONTALINHAS
 SET @CONTALINHAS += 1
END

SELECT * FROM CAMPANHA
WHERE SITUACAO IS NOT NULL